# fly.toml app configuration file generated for 3d-2026-02-10-001 on 2026-02-13T14:06:24-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '3d-2026-02-10-001'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
